/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f8fafc",
        "on-secondary-fixed-variant": "#6800b4",
        "on-surface-variant": "#64748b",
        "tertiary": "#f7be1d",
        "secondary": "#7c03d3",
        "primary-fixed-dim": "#ffb690",
        "on-error": "#690005",
        "inverse-surface": "#0f172a",
        "on-tertiary-fixed": "#251a00",
        "surface-container-high": "#ffffff",
        "inverse-primary": "#9d4300",
        "on-tertiary": "#3f2e00",
        "on-primary-fixed-variant": "#783200",
        "status-green": "#22c55e",
        "surface-dim": "#f1f5f9",
        "tertiary-fixed": "#ffdf9a",
        "inverse-on-surface": "#f8fafc",
        "on-tertiary-fixed-variant": "#5a4300",
        "outline": "#cbd5e1",
        "primary": "#f97316",
        "surface-container-highest": "#f1f5f9",
        "primary-container": "#f97316",
        "on-primary-fixed": "#341100",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#f7be1d",
        "secondary-container": "#7c03d3",
        "surface": "#ffffff",
        "tertiary-container": "#c19300",
        "surface-container": "#f8fafc",
        "on-primary-container": "#ffffff",
        "secondary-fixed": "#f0dbff",
        "surface-container-low": "#ffffff",
        "outline-variant": "#e2e8f0",
        "surface-tint": "#f97316",
        "secondary-fixed-dim": "#ddb8ff",
        "on-secondary": "#ffffff",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "glass-border": "rgba(0, 0, 0, 0.05)",
        "on-background": "#0f172a",
        "error": "#ef4444",
        "on-secondary-container": "#ffffff",
        "on-secondary-fixed": "#2c0051",
        "error-container": "#fee2e2",
        "surface-variant": "#f1f5f9",
        "on-surface": "#0f172a",
        "on-tertiary-container": "#412f00",
        "primary-fixed": "#ffdbca",
        "on-error-container": "#991b1b",
        "border-subtle": "#EAEAEA",
        "brand-orange": "#FF6B00",
        "text-muted": "#666666"
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "gutter": "24px",
        "section-gap": "48px",
        "container-max": "1280px",
        "stack-md": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'sans-serif'],
        body: ['Geist', 'Inter', 'sans-serif'],
        heading: ['Geist', 'Inter', 'sans-serif'],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "status-label": ["Geist"],
        "display-lg": ["Inter"],
        "label-caps": ["Geist"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "status-label": ["11px", { "lineHeight": "1", "fontWeight": "600" }],
        "display-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }]
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
      },
      animation: {
        marquee: 'marquee 65s linear infinite',
        'marquee-reverse': 'marquee-reverse 65s linear infinite',
      },

    },
  },
  plugins: [],
};
